[package]
name = "osmio"
version = "0.16.0-dev"
authors = ["Amanda McCann <amanda@technomancy.org>"]
keywords = ["openstreetmap", "osm"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/amandasaurus/osmio/"
description = "Read and write OpenStreetMap data files"
edition = "2021"

[dependencies]
anyhow = "1.0"
byteorder = "1.5.0"
bzip2 = "0.6"
chrono = "0.4.45"
derive_builder = "0.20"
flate2 = "1.1.9"
iter-progress = "0.8.0"
protobuf = "3.7.2"
quick-xml = "0.41"
separator = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1.15.2"
smol_str = "0.3.6"
xml-rs = "1.0.0"

rusqlite = { version = "0.40", optional = true }

[features]
with-changeset-sqlite = [ "dep:rusqlite" ]

[[bin]]
name = "osmio-changeset-tags-to-sqlite"
required-features = [ "with-changeset-sqlite" ]
