// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `fileformat.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:BlobHeader)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BlobHeader {
    // message fields
    // @@protoc_insertion_point(field:BlobHeader.type)
    pub type_: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:BlobHeader.indexdata)
    pub indexdata: ::std::option::Option<::std::vec::Vec<u8>>,
    // @@protoc_insertion_point(field:BlobHeader.datasize)
    pub datasize: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:BlobHeader.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BlobHeader {
    fn default() -> &'a BlobHeader {
        <BlobHeader as ::protobuf::Message>::default_instance()
    }
}

impl BlobHeader {
    pub fn new() -> BlobHeader {
        ::std::default::Default::default()
    }

    // required string type = 1;

    pub fn type_(&self) -> &str {
        match self.type_.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_type_(&mut self) {
        self.type_ = ::std::option::Option::None;
    }

    pub fn has_type(&self) -> bool {
        self.type_.is_some()
    }

    // Param is passed by value, moved
    pub fn set_type(&mut self, v: ::std::string::String) {
        self.type_ = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_type(&mut self) -> &mut ::std::string::String {
        if self.type_.is_none() {
            self.type_ = ::std::option::Option::Some(::std::string::String::new());
        }
        self.type_.as_mut().unwrap()
    }

    // Take field
    pub fn take_type_(&mut self) -> ::std::string::String {
        self.type_.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional bytes indexdata = 2;

    pub fn indexdata(&self) -> &[u8] {
        match self.indexdata.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_indexdata(&mut self) {
        self.indexdata = ::std::option::Option::None;
    }

    pub fn has_indexdata(&self) -> bool {
        self.indexdata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_indexdata(&mut self, v: ::std::vec::Vec<u8>) {
        self.indexdata = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_indexdata(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.indexdata.is_none() {
            self.indexdata = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.indexdata.as_mut().unwrap()
    }

    // Take field
    pub fn take_indexdata(&mut self) -> ::std::vec::Vec<u8> {
        self.indexdata.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // required int32 datasize = 3;

    pub fn datasize(&self) -> i32 {
        self.datasize.unwrap_or(0)
    }

    pub fn clear_datasize(&mut self) {
        self.datasize = ::std::option::Option::None;
    }

    pub fn has_datasize(&self) -> bool {
        self.datasize.is_some()
    }

    // Param is passed by value, moved
    pub fn set_datasize(&mut self, v: i32) {
        self.datasize = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "type",
            |m: &BlobHeader| { &m.type_ },
            |m: &mut BlobHeader| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "indexdata",
            |m: &BlobHeader| { &m.indexdata },
            |m: &mut BlobHeader| { &mut m.indexdata },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "datasize",
            |m: &BlobHeader| { &m.datasize },
            |m: &mut BlobHeader| { &mut m.datasize },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BlobHeader>(
            "BlobHeader",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BlobHeader {
    const NAME: &'static str = "BlobHeader";

    fn is_initialized(&self) -> bool {
        if self.type_.is_none() {
            return false;
        }
        if self.datasize.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.type_ = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.indexdata = ::std::option::Option::Some(is.read_bytes()?);
                },
                24 => {
                    self.datasize = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.type_.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.indexdata.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        if let Some(v) = self.datasize {
            my_size += ::protobuf::rt::int32_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.type_.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.indexdata.as_ref() {
            os.write_bytes(2, v)?;
        }
        if let Some(v) = self.datasize {
            os.write_int32(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BlobHeader {
        BlobHeader::new()
    }

    fn clear(&mut self) {
        self.type_ = ::std::option::Option::None;
        self.indexdata = ::std::option::Option::None;
        self.datasize = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BlobHeader {
        static instance: BlobHeader = BlobHeader {
            type_: ::std::option::Option::None,
            indexdata: ::std::option::Option::None,
            datasize: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BlobHeader {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BlobHeader").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BlobHeader {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlobHeader {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Blob)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Blob {
    // message fields
    // @@protoc_insertion_point(field:Blob.raw)
    pub raw: ::std::option::Option<::std::vec::Vec<u8>>,
    // @@protoc_insertion_point(field:Blob.raw_size)
    pub raw_size: ::std::option::Option<i32>,
    ///  Possible compressed versions of the data.
    // @@protoc_insertion_point(field:Blob.zlib_data)
    pub zlib_data: ::std::option::Option<::std::vec::Vec<u8>>,
    ///  PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
    // @@protoc_insertion_point(field:Blob.lzma_data)
    pub lzma_data: ::std::option::Option<::std::vec::Vec<u8>>,
    ///  Formerly used for bzip2 compressed data. Depreciated in 2010.
    // @@protoc_insertion_point(field:Blob.OBSOLETE_bzip2_data)
    pub OBSOLETE_bzip2_data: ::std::option::Option<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:Blob.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Blob {
    fn default() -> &'a Blob {
        <Blob as ::protobuf::Message>::default_instance()
    }
}

impl Blob {
    pub fn new() -> Blob {
        ::std::default::Default::default()
    }

    // optional bytes raw = 1;

    pub fn raw(&self) -> &[u8] {
        match self.raw.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_raw(&mut self) {
        self.raw = ::std::option::Option::None;
    }

    pub fn has_raw(&self) -> bool {
        self.raw.is_some()
    }

    // Param is passed by value, moved
    pub fn set_raw(&mut self, v: ::std::vec::Vec<u8>) {
        self.raw = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_raw(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.raw.is_none() {
            self.raw = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.raw.as_mut().unwrap()
    }

    // Take field
    pub fn take_raw(&mut self) -> ::std::vec::Vec<u8> {
        self.raw.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional int32 raw_size = 2;

    pub fn raw_size(&self) -> i32 {
        self.raw_size.unwrap_or(0)
    }

    pub fn clear_raw_size(&mut self) {
        self.raw_size = ::std::option::Option::None;
    }

    pub fn has_raw_size(&self) -> bool {
        self.raw_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_raw_size(&mut self, v: i32) {
        self.raw_size = ::std::option::Option::Some(v);
    }

    // optional bytes zlib_data = 3;

    pub fn zlib_data(&self) -> &[u8] {
        match self.zlib_data.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_zlib_data(&mut self) {
        self.zlib_data = ::std::option::Option::None;
    }

    pub fn has_zlib_data(&self) -> bool {
        self.zlib_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_zlib_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.zlib_data = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zlib_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.zlib_data.is_none() {
            self.zlib_data = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.zlib_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_zlib_data(&mut self) -> ::std::vec::Vec<u8> {
        self.zlib_data.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional bytes lzma_data = 4;

    pub fn lzma_data(&self) -> &[u8] {
        match self.lzma_data.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_lzma_data(&mut self) {
        self.lzma_data = ::std::option::Option::None;
    }

    pub fn has_lzma_data(&self) -> bool {
        self.lzma_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_lzma_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.lzma_data = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_lzma_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.lzma_data.is_none() {
            self.lzma_data = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.lzma_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_lzma_data(&mut self) -> ::std::vec::Vec<u8> {
        self.lzma_data.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional bytes OBSOLETE_bzip2_data = 5;

    pub fn OBSOLETE_bzip2_data(&self) -> &[u8] {
        match self.OBSOLETE_bzip2_data.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_OBSOLETE_bzip2_data(&mut self) {
        self.OBSOLETE_bzip2_data = ::std::option::Option::None;
    }

    pub fn has_OBSOLETE_bzip2_data(&self) -> bool {
        self.OBSOLETE_bzip2_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_OBSOLETE_bzip2_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.OBSOLETE_bzip2_data = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_OBSOLETE_bzip2_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.OBSOLETE_bzip2_data.is_none() {
            self.OBSOLETE_bzip2_data = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.OBSOLETE_bzip2_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_OBSOLETE_bzip2_data(&mut self) -> ::std::vec::Vec<u8> {
        self.OBSOLETE_bzip2_data.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "raw",
            |m: &Blob| { &m.raw },
            |m: &mut Blob| { &mut m.raw },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "raw_size",
            |m: &Blob| { &m.raw_size },
            |m: &mut Blob| { &mut m.raw_size },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "zlib_data",
            |m: &Blob| { &m.zlib_data },
            |m: &mut Blob| { &mut m.zlib_data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "lzma_data",
            |m: &Blob| { &m.lzma_data },
            |m: &mut Blob| { &mut m.lzma_data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "OBSOLETE_bzip2_data",
            |m: &Blob| { &m.OBSOLETE_bzip2_data },
            |m: &mut Blob| { &mut m.OBSOLETE_bzip2_data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Blob>(
            "Blob",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Blob {
    const NAME: &'static str = "Blob";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.raw = ::std::option::Option::Some(is.read_bytes()?);
                },
                16 => {
                    self.raw_size = ::std::option::Option::Some(is.read_int32()?);
                },
                26 => {
                    self.zlib_data = ::std::option::Option::Some(is.read_bytes()?);
                },
                34 => {
                    self.lzma_data = ::std::option::Option::Some(is.read_bytes()?);
                },
                42 => {
                    self.OBSOLETE_bzip2_data = ::std::option::Option::Some(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.raw.as_ref() {
            my_size += ::protobuf::rt::bytes_size(1, &v);
        }
        if let Some(v) = self.raw_size {
            my_size += ::protobuf::rt::int32_size(2, v);
        }
        if let Some(v) = self.zlib_data.as_ref() {
            my_size += ::protobuf::rt::bytes_size(3, &v);
        }
        if let Some(v) = self.lzma_data.as_ref() {
            my_size += ::protobuf::rt::bytes_size(4, &v);
        }
        if let Some(v) = self.OBSOLETE_bzip2_data.as_ref() {
            my_size += ::protobuf::rt::bytes_size(5, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.raw.as_ref() {
            os.write_bytes(1, v)?;
        }
        if let Some(v) = self.raw_size {
            os.write_int32(2, v)?;
        }
        if let Some(v) = self.zlib_data.as_ref() {
            os.write_bytes(3, v)?;
        }
        if let Some(v) = self.lzma_data.as_ref() {
            os.write_bytes(4, v)?;
        }
        if let Some(v) = self.OBSOLETE_bzip2_data.as_ref() {
            os.write_bytes(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Blob {
        Blob::new()
    }

    fn clear(&mut self) {
        self.raw = ::std::option::Option::None;
        self.raw_size = ::std::option::Option::None;
        self.zlib_data = ::std::option::Option::None;
        self.lzma_data = ::std::option::Option::None;
        self.OBSOLETE_bzip2_data = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Blob {
        static instance: Blob = Blob {
            raw: ::std::option::Option::None,
            raw_size: ::std::option::Option::None,
            zlib_data: ::std::option::Option::None,
            lzma_data: ::std::option::Option::None,
            OBSOLETE_bzip2_data: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Blob {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Blob").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Blob {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Blob {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10fileformat.proto\"Z\n\nBlobHeader\x12\x12\n\x04type\x18\x01\x20\
    \x02(\tR\x04type\x12\x1c\n\tindexdata\x18\x02\x20\x01(\x0cR\tindexdata\
    \x12\x1a\n\x08datasize\x18\x03\x20\x02(\x05R\x08datasize\"\xa1\x01\n\x04\
    Blob\x12\x10\n\x03raw\x18\x01\x20\x01(\x0cR\x03raw\x12\x19\n\x08raw_size\
    \x18\x02\x20\x01(\x05R\x07rawSize\x12\x1b\n\tzlib_data\x18\x03\x20\x01(\
    \x0cR\x08zlibData\x12\x1b\n\tlzma_data\x18\x04\x20\x01(\x0cR\x08lzmaData\
    \x122\n\x13OBSOLETE_bzip2_data\x18\x05\x20\x01(\x0cR\x11OBSOLETEBzip2Dat\
    aB\x02\x18\x01J\x8e\x07\n\x06\x12\x04\0\0\x12\x01\n\n\n\x02\x04\0\x12\
    \x04\0\0\x04\x01\n\n\n\x03\x04\0\x01\x12\x03\0\x08\x12\n\x0b\n\x04\x04\0\
    \x02\0\x12\x03\x01\x04\x1d\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x01\x04\
    \x0c\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x01\r\x13\n\x0c\n\x05\x04\0\x02\
    \0\x01\x12\x03\x01\x14\x18\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x01\x1b\
    \x1c\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x02\x04!\n\x0c\n\x05\x04\0\x02\
    \x01\x04\x12\x03\x02\x04\x0c\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x02\r\
    \x12\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x02\x13\x1c\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\x02\x1f\x20\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x03\
    \x04\x20\n\x0c\n\x05\x04\0\x02\x02\x04\x12\x03\x03\x04\x0c\n\x0c\n\x05\
    \x04\0\x02\x02\x05\x12\x03\x03\r\x12\n\x0c\n\x05\x04\0\x02\x02\x01\x12\
    \x03\x03\x13\x1b\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x03\x1e\x1f\n\n\n\
    \x02\x04\x01\x12\x04\x06\0\x12\x01\n\n\n\x03\x04\x01\x01\x12\x03\x06\x08\
    \x0c\n\x1d\n\x04\x04\x01\x02\0\x12\x03\x07\x04\x1b\"\x10\x20No\x20compre\
    ssion\n\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03\x07\x04\x0c\n\x0c\n\x05\
    \x04\x01\x02\0\x05\x12\x03\x07\r\x12\n\x0c\n\x05\x04\x01\x02\0\x01\x12\
    \x03\x07\x13\x16\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x07\x19\x1a\n5\n\
    \x04\x04\x01\x02\x01\x12\x03\x08\x04\x20\"(\x20When\x20compressed,\x20th\
    e\x20uncompressed\x20size\n\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03\x08\
    \x04\x0c\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x08\r\x12\n\x0c\n\x05\
    \x04\x01\x02\x01\x01\x12\x03\x08\x13\x1b\n\x0c\n\x05\x04\x01\x02\x01\x03\
    \x12\x03\x08\x1e\x1f\n8\n\x04\x04\x01\x02\x02\x12\x03\x0b\x04!\x1a+\x20P\
    ossible\x20compressed\x20versions\x20of\x20the\x20data.\n\n\x0c\n\x05\
    \x04\x01\x02\x02\x04\x12\x03\x0b\x04\x0c\n\x0c\n\x05\x04\x01\x02\x02\x05\
    \x12\x03\x0b\r\x12\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x0b\x13\x1c\n\
    \x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x0b\x1f\x20\nR\n\x04\x04\x01\x02\
    \x03\x12\x03\x0e\x04!\x1aE\x20PROPOSED\x20feature\x20for\x20LZMA\x20comp\
    ressed\x20data.\x20SUPPORT\x20IS\x20NOT\x20REQUIRED.\n\n\x0c\n\x05\x04\
    \x01\x02\x03\x04\x12\x03\x0e\x04\x0c\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\
    \x03\x0e\r\x12\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x0e\x13\x1c\n\x0c\
    \n\x05\x04\x01\x02\x03\x03\x12\x03\x0e\x1f\x20\nl\n\x04\x04\x01\x02\x04\
    \x12\x03\x11\x04=\x1a?\x20Formerly\x20used\x20for\x20bzip2\x20compressed\
    \x20data.\x20Depreciated\x20in\x202010.\n\"\x1e\x20Don't\x20reuse\x20thi\
    s\x20tag\x20number.\n\n\x0c\n\x05\x04\x01\x02\x04\x04\x12\x03\x11\x04\
    \x0c\n\x0c\n\x05\x04\x01\x02\x04\x05\x12\x03\x11\r\x12\n\x0c\n\x05\x04\
    \x01\x02\x04\x01\x12\x03\x11\x13&\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\
    \x03\x11)*\n\x0c\n\x05\x04\x01\x02\x04\x08\x12\x03\x11+<\n\r\n\x06\x04\
    \x01\x02\x04\x08\x03\x12\x03\x11,;\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(BlobHeader::generated_message_descriptor_data());
            messages.push(Blob::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
